### ISSUE TITLE
release of pretrained model for MIP

### ISSUE THREAD

**Issue by weiweitoo** [facebookresearch/CovidPrognosis#4]
Hi, I read your paper and i think it is very interesting. However, i only happened to find the pre-trained model for SIP model, but no the MIP. Do you have any plan in future to release them as well?

**Comment by mmuckley** [comment]
Hello @weiweitoo, we only released pretrained models associated with public data, so we won't be releasing MIP or the full SIP model. If you have any troubles working with the code base, we can help you there in terms of training on your own data.

**Comment by mmuckley** [comment]
@anuroopsriram could you take care of this MIP question?

**Comment by anuroopsriram** [comment]
Hi: 
As the [README file](https://github.com/facebookresearch/CovidPrognosis/blob/master/cp_examples/mip_finetune/README.md) explains, you'll need to write a data loader yourself, depending on your data format.

The pre-trained weights are same for SIP and MIP.
