### ISSUE TITLE
Can you provide load and predict guideline on Colab?

### ISSUE THREAD

**Issue by JihwanEom** [facebookresearch/CovidPrognosis#5]
Hi, thanks for your excellent works!

I've impressed on this task, so I wanna apply your model for my hospital datasets.

But there was no guideline for pre-trained model load and predict. (it was too hard for me..)

Can you provide some codes on Colab?

Thank you!

**Comment by mmuckley** [comment]
For the final SIP task it's not exactly possible. There is a lot of manual data engineering for extracting information from electronic health records that probably doesn't generalize between hospitals - you'll have to work with your IT department on that. We do provide a script for fine-tuning on the public X-ray data sets, which you can find here: https://github.com/facebookresearch/CovidPrognosis/tree/master/cp_examples/sip_finetune.

**Comment by JihwanEom** [comment]
@mmuckley Thank you for your comments! However, there is no IT department in our hospital, and I am working hard by myself. But I will try to make a data module..

**Comment by mmuckley** [comment]
Hello @JihwanEom, I would be cautious working with EHR if you don't know someone with experience. There are quite a few gotchas, and it can be a little bit confusing.

That being said, for writing dataloaders the [`torchxrayvision`](https://github.com/mlmed/torchxrayvision/blob/master/torchxrayvision/datasets.py) package has a lot of good examples for X-ray radiograph datasets to see how these things are structured.
