### ISSUE TITLE
Run inference

### ISSUE THREAD

**Issue by luantunez** [facebookresearch/CovidPrognosis#9]
Thank you for sharing your work! I would like to know how to run an inference on some data to obtain the output mentioned on your paper. 
Thank you in advance

**Comment by mmuckley** [comment]
Hello @luantunez, have you fine-tuned one of the MoCo models on your own data?

**Comment by luantunez** [comment]
No I have not, is it possible to predict on regular chest x ray images without fine-tuning?

**Comment by mmuckley** [comment]
No, you will have to fine-tune. You can use the released pretraining if you wish.

**Comment by mmuckley** [comment]
Closing for now.
